introduce docker_wrapper script to make tests runnable from repo too

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -1,23 +1,23 @@
 #!/bin/bash
 # Author: Michael Gebetsroither <michael@mgeb.org>
 
-dir_="$(dirname $(readlink -f $0))"
-#echo "Executing tests in directory: $dir_" >&2
-
-cd "$dir_" || exit 1
-
 binaries-callable() {
-    ret_=0
+    errors_=0
     for i in $(ls bin/*); do
         out_="$($i --help)"
         bin_="$(basename $i)"
         if ! echo "$out_" |grep -q "Usage: $bin_"; then
-            ret_=1
+            errors_=$(( $errors_ + 1 ))
             echo "Error getting usage from: $bin_"
             echo "$out_"
         fi
     done
-    exit $ret_
+    echo "binaries-callable fails $errors_ of $(ls bin/*|wc -l) tests"
+    if (( $errors_ != 0 )); then
+        exit 1
+    else
+        exit 0
+    fi
 }
 
 unit() {
@@ -25,7 +25,19 @@ unit() {
     exec /usr/bin/python ./run_doctest.py "ooopy/$1"
 }
 
+all_tests() {
+    ret_=0
+    for i in binaries-callable unit-transformer unit-ooopy; do
+        if ! $0 $i; then
+            ret_=1
+            echo "Error: test-failure for $i"
+        fi
+    done
+    exit $ret_
+}
+
 case "$1" in
+    "all") all_tests ;;
     "binaries-callable") binaries-callable ;;
     "unit-transformer") unit "Transformer.py" ;;
     "unit-ooopy" ) unit "OOoPy.py" ;;
